FROM apache/spark:latest
USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl postgresql-client && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]